console.log("My first console");
var first_name = "gregerny";
var last_name = "johnson";
var full_name=first_name.concat(last_name);
console.log(full_name);
var x = 10;
var y = 5;
var add=x+y;
console.log(add);
var sub=x-y;
console.log(sub);
var mul=x*y;
console.log(mul);
var div=x/y;
console.log(div);